server:
  port: 8080
  shutdown: graceful

logging:
  level:
    org.jooq: DEBUG

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:coord;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: admin
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  banner:
    location: classpath:/banner/local.txt
